server:
  port: 8185


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: EMPLOYEESERVICE
          uri: lb://EMPLOYEESERVICE
          predicates:
            - Path=/EmployeeManagement/**
        - id: EMPLOYEESERVICE
          uri: lb://INSURANCEMANAGEMENT
          predicates:
            - Path=/InsuranceManagement/**
        - id: SALARYSERVICE
          uri: lb://SALARYSERVICE
          predicates:
            - Path=/SalaryManagement/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost