spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SalaryManagement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mangesh@09

  application:
    name: SalaryService


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: MYSQL


server:
  port: 8183
