spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SalaryManagement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mangesh@09

  application:
    name: SalaryService


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: MYSQL

feign:
  circuitbreaker:
    enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8183

