spring:
  datasource:
    url: jdbc:mysql://localhost:3306/InsuranceManagement
    username: root
    password: Mangesh@09
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: InsuranceManagement


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database: MYSQL

server:
  port: 8182



