spring:
  datasource:
    url: jdbc:mysql://localhost:3306/InsuranceManagement
    username: root
    password: Mangesh@09
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: InsuranceManagement


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: MYSQL

server:
  port: 8182



eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8084/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
