spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeManagement
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Mangesh@09



  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: MYSQL
  config:
    import: optional:configserver:http://localhost:8186




server:
  port: 8181

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      employeeBreak:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      employeeBreakRetry:
        maxAttempts: 3
        waitDuration: 2s
